// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Menu: typeof import('./src/components/base/Menu.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NButtonGroup: typeof import('naive-ui')['NButtonGroup']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NMenu: typeof import('naive-ui')['NMenu']
    NModal: typeof import('naive-ui')['NModal']
    NPagination: typeof import('naive-ui')['NPagination']
    NRadio: typeof import('naive-ui')['NRadio']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTable: typeof import('naive-ui')['NTable']
    VFooter: typeof import('./src/components/base/VFooter.vue')['default']
    VHeader: typeof import('./src/components/base/VHeader.vue')['default']
    VMenu: typeof import('./src/components/base/VMenu.vue')['default']
    VPageTabs: typeof import('./src/components/base/VPageTabs.vue')['default']
    VProvider: typeof import('./src/components/base/VProvider.vue')['default']
    VRouterView: typeof import('./src/components/base/VRouterView.vue')['default']
    YFooter: typeof import('./src/components/base/YFooter.vue')['default']
    YHeader: typeof import('./src/components/base/YHeader.vue')['default']
    YMenu: typeof import('./src/components/base/YMenu.vue')['default']
    YPageTabs: typeof import('./src/components/base/YPageTabs.vue')['default']
    YProvider: typeof import('./src/components/base/YProvider.vue')['default']
    YRouterView: typeof import('./src/components/base/YRouterView.vue')['default']
  }
}

export { }
